-- Stock Prices
CREATE TABLE IF NOT EXISTS FINANCE_ANALYTICS.BRONZE.STOCK_PRICES (
    DATE DATE,
    SYMBOL VARCHAR,
    COMPANY_NAME VARCHAR,
    OPEN FLOAT,
    HIGH FLOAT,
    LOW FLOAT,
    CLOSE FLOAT,
    VOLUME NUMBER(38,0),
    CREATED_AT TIMESTAMP_NTZ(9),
    UPDATED_AT TIMESTAMP_NTZ(9),
    ACTIVE BOOLEAN
);


CREATE TABLE IF NOT EXISTS FINANCE_ANALYTICS.BRONZE.COMPANY_FUNDAMENTALS (
    SYMBOL VARCHAR NOT NULL,
    COMPANY_NAME VARCHAR,
    INDUSTRY VARCHAR,
    SECTOR VARCHAR,
    CEO VARCHAR,
    EXCHANGE VARCHAR,
    WEBSITE VARCHAR,
    DESCRIPTION VARCHAR,
    PRICE FLOAT,
    BETA FLOAT,
    VOL_AVG NUMBER(38,0),
    MKT_CAP NUMBER(38,2),
    LAST_DIV FLOAT,
    RANGE VARCHAR,
    IPO_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ(9),
    UPDATED_AT TIMESTAMP_NTZ(9),
    ACTIVE BOOLEAN
);

CREATE TABLE IF NOT EXISTS FINANCE_ANALYTICS.BRONZE.ECONOMIC_INDICATORS (
    DATE DATE,
    VALUE FLOAT,  -- Ensure '.' or non-numeric entries are filtered or coerced to NULL
    SERIES_ID VARCHAR,
    SERIES_NAME VARCHAR,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    ACTIVE BOOLEAN
);

CREATE TABLE IF NOT EXISTS FINANCE_ANALYTICS.BRONZE.STOCK_NEWS_SENTIMENT (
    publishedAt TIMESTAMP_TZ,
    title VARCHAR,
    description VARCHAR,
    url VARCHAR,
    source VARCHAR,
    symbol VARCHAR,
    company_name VARCHAR,
    fetched_at TIMESTAMP_NTZ(9)
);


CREATE STAGE IF NOT EXISTS FINANCE_ANALYTICS.BRONZE.STOCKS 
	DIRECTORY = ( ENABLE = true );
CREATE STAGE IF NOT EXISTS FINANCE_ANALYTICS.BRONZE.COMPANY_FUNDAMENTALS 
	DIRECTORY = ( ENABLE = true );
CREATE STAGE IF NOT EXISTS FINANCE_ANALYTICS.BRONZE.ECONOMIC_INDICATORS 
	DIRECTORY = ( ENABLE = true );
CREATE STAGE IF NOT EXISTS FINANCE_ANALYTICS.BRONZE.STOCK_NEWS_SENTIMENT
	DIRECTORY = ( ENABLE = true );


    select count(*) from FINANCE_ANALYTICS.BRONZE.STOCK_PRICES
-- Crypto Prices (Optional)
CREATE TABLE IF NOT EXISTS BRONZE.CRYPTO_PRICES (
    TIMESTAMP TIMESTAMP,
    SYMBOL VARCHAR,
    PRICE_USD FLOAT,
    VOLUME_24H FLOAT,
    MARKET_CAP FLOAT,
    created_at TIMESTAMP_NTZ(9),
    updated_at TIMESTAMP_NTZ(9),
    active BOOLEAN
);

-- Forex Rates (Optional)
CREATE TABLE IF NOT EXISTS FINANCE_ANALYTICS.BRONZE.FOREX_RATES (
    DATE DATE,
    BASE_CURRENCY VARCHAR,
    TARGET_CURRENCY VARCHAR,
    RATE FLOAT,
    created_at TIMESTAMP_NTZ(9),
    updated_at TIMESTAMP_NTZ(9),
    active BOOLEAN
);

