CREATE DATABASE IF NOT EXISTS FINANCE_ANALYTICS;

-- Schemas for Medallion architecture
CREATE SCHEMA IF NOT EXISTS FINANCE_ANALYTICS.BRONZE;
CREATE SCHEMA IF NOT EXISTS FINANCE_ANALYTICS.SILVER;
CREATE SCHEMA IF NOT EXISTS FINANCE_ANALYTICS.GOLD;
