SELECT 
    PUBLISHEDAT,
    SYMBOL,
    TITLE,
    DESCRIPTION,
    SNOWFLAKE.CORTEX.SENTIMENT(TITLE) AS TITLE_SENTIMENT,
    SNOWFLAKE.CORTEX.SENTIMENT(DESCRIPTION) AS DESC_SENTIMENT
FROM FINANCE_ANALYTICS.BRONZE.STOCK_NEWS_SENTIMENT
-- LIMIT 10;
select series_id,count(*) from economic_indicators group by series_id ORDER BY COUNT(*) where SERIES_ID='CPALTT01ITQ657N'
select * from stock_news_sentiment limit 10
-- SELECT SNOWFLAKE.CORTEX.SENTIMENT(review_content), review_content FROM reviews LIMIT 10;

select symbol,COMPANY_NAME, count(*) from stock_prices group BY company_name,symbol


UNDROP TABLE FINANCE_ANALYTICS.BRONZE.COMPANY_FUNDAMENTALS;
UNDROP TABLE FINANCE_ANALYTICS.BRONZE.STOCK_NEWS_SENTIMENT;
UNDROP TABLE FINANCE_ANALYTICS.BRONZE.STOCK_PRICES;
UNDROP TABLE FINANCE_ANALYTICS.BRONZE.ECONOMIC_INDICATORS;
