CREATE TABLE IF NOT EXISTS FINANCE_ANALYTICS.SILVER.STOCK_PRICES_CLEANED AS
SELECT 
    DATE,
    UPPER(SYMBOL) AS SYMBOL,
    INITCAP(COMPANY_NAME) AS COMPANY_NAME,
    OPEN,
    HIGH,
    LOW,
    CLOSE,
    VOLUME,
    CREATED_AT,
    UPDATED_AT
FROM FINANCE_ANALYTICS.BRONZE.STOCK_PRICES
WHERE ACTIVE = TRUE
  AND DATE IS NOT NULL
  AND OPEN IS NOT NULL;

CREATE TABLE IF NOT EXISTS FINANCE_ANALYTICS.SILVER.COMPANY_FUNDAMENTALS_CLEANED AS
SELECT 
    UPPER(SYMBOL) AS SYMBOL,
    INITCAP(COMPANY_NAME) AS COMPANY_NAME,
    INITCAP(INDUSTRY) AS INDUSTRY,
    INITCAP(SECTOR) AS SECTOR,
    INITCAP(CEO) AS CEO,
    EXCHANGE,
    WEBSITE,
    DESCRIPTION,
    PRICE,
    BETA,
    VOL_AVG,
    MKT_CAP,
    LAST_DIV,
    RANGE,
    IPO_DATE,
    CREATED_AT,
    UPDATED_AT
FROM FINANCE_ANALYTICS.BRONZE.COMPANY_FUNDAMENTALS
WHERE ACTIVE = TRUE;

CREATE TABLE IF NOT EXISTS FINANCE_ANALYTICS.SILVER.ECONOMIC_INDICATORS_CLEANED AS
SELECT 
    DATE,
    TRY_CAST(VALUE AS FLOAT) AS VALUE,
    SERIES_ID,
    INITCAP(SERIES_NAME) AS SERIES_NAME,
    CREATED_AT,
    UPDATED_AT
FROM FINANCE_ANALYTICS.BRONZE.ECONOMIC_INDICATORS
WHERE ACTIVE = TRUE
  AND VALUE IS NOT NULL;

CREATE TABLE IF NOT EXISTS FINANCE_ANALYTICS.SILVER.STOCK_NEWS_SENTIMENT_CLEANED AS
SELECT 
    PUBLISHEDAT::TIMESTAMP_NTZ AS PUBLISHED_AT,
    INITCAP(TITLE) AS TITLE,
    DESCRIPTION,
    URL,
    SOURCE,
    UPPER(SYMBOL) AS SYMBOL,
    INITCAP(COMPANY_NAME) AS COMPANY_NAME,
    SNOWFLAKE.CORTEX.SENTIMENT(TITLE) AS TITLE_SENTIMENT,
    SNOWFLAKE.CORTEX.SENTIMENT(DESCRIPTION) AS DESC_SENTIMENT,
    FETCHED_AT
FROM FINANCE_ANALYTICS.BRONZE.STOCK_NEWS_SENTIMENT
WHERE TITLE IS NOT NULL 
  AND PUBLISHEDAT IS NOT NULL;


