CREATE OR REPLACE PROCEDURE FINANCE_ANALYTICS.DBT_SILVER.RUN_FORECAST_PROC()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    CREATE OR REPLACE SNOWFLAKE.ML.FORECAST FINANCE_ANALYTICS.DBT_SILVER.STOCK_PRICE_FORECAST_MODEL (
        INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'VW_STOCK_PRICES_CLEANED_FOR_FORECAST'),
        SERIES_COLNAME => 'SYMBOL',
        TIMESTAMP_COLNAME => 'DATE_v1',
        TARGET_COLNAME => 'CLOSE',
        CONFIG_OBJECT => { 'ON_ERROR': 'SKIP' }
    );

    CALL FINANCE_ANALYTICS.DBT_SILVER.STOCK_PRICE_FORECAST_MODEL!FORECAST(
        FORECASTING_PERIODS => 7,
        CONFIG_OBJECT => {'prediction_interval': 0.95}
    );

    LET forecast_result := SQLID;

    CREATE OR REPLACE TABLE FINANCE_ANALYTICS.DBT_SILVER.STOCK_PRICE_FORECAST AS
    SELECT * FROM TABLE(RESULT_SCAN(:forecast_result));

    RETURN 'Forecast table created successfully.';
END;
$$;
call FINANCE_ANALYTICS.DBT_SILVER.RUN_FORECAST_PROC()