{{ config(materialized='incremental', unique_key='row_hash') }}

SELECT
    PUBLISHEDAT::TIMESTAMP_NTZ AS PUBLISHED_AT,
    INITCAP(TITLE) AS TITLE,
    DESCRIPTION,
    URL,
    SOURCE,
    UPPER(SYMBOL) AS SYMBOL,
    INITCAP(COMPANY_NAME) AS COMPANY_NAME,
    SNOWFLAKE.CORTEX.SENTIMENT(TITLE) AS TITLE_SENTIMENT,
    SNOWFLAKE.CORTEX.SENTIMENT(DESCRIPTION) AS DESC_SENTIMENT,
    FETCHED_AT,
    row_hash
FROM {{ ref('vw_stock_news_sentiment') }}
